### ISSUE TITLE
Allow setting of HTTP client timeouts

### ISSUE THREAD

**Issue by krische** [jenkinsci/azure-sdk-plugin#23]
### Dependencies

Depending on the implementation, it might require further changes on the Azure VM Agents plugin to consume this feature.

### Feature Request

It would be nice if there were a way to set the `read`, `response`, and `write` timeouts of the created HttpClient in `HttpClientRetriever.get()`. There are times where I am seeing that the default 60 second timeouts of the client are not enough.

I will look to your advice for the best method to implement this. System properties? Parameters to the `get()` method? Something else?

**Comment by timja** [comment]
System properties would probably be easiest and then documented in the README

**Comment by krische** [comment]
> What calls are you seeing getting timed out? Maybe those should be optimised or have timeouts increased?

@timja I have been seeing timeouts on the request that creates a new deployment for the Azure VM agents. Not the actual completion time of the deployment, but purely just the HTTP POST/PUT request to create the deployment. Oddly enough, it seems to depend on how many VMs are created as part of that deployment. If it was a small number of VMs, like 5, it would create the deployment just fine. But a larger number, like 20, would seem to take several minutes just to create the deployment and have it start the actual deployment steps. Which seems odd to me since I thought the number of VMs was basically a parameter to the deployment, I wouldn't think it would have any impact on the HTTP payload size or anything that should make that request take so long.

**Comment by timja** [comment]
May be worth raising on https://github.com/azure/azure-sdk-for-java or stackoverflow?
